<?php
namespace Wambo\Core;

use Wambo\Developer\Whoops\Middleware as WhoopsMiddleware;
use Wambo\Frontend\Registration as FrontendRegistration;
use Wambo\Cart\Registration as CartRegistration;
use \Wambo\Checkout\Registration as CheckoutRegistration;

error_reporting(E_ALL);
ini_set('display_errors', 1);

// define root directory for the project
define('WAMBO_ROOT_DIR', dirname(getcwd() . '..'));

// load autoload file generated by composer
$autoload_filename = WAMBO_ROOT_DIR . '/vendor/autoload.php';
if (!file_exists($autoload_filename)) {
    echo $autoload_filename . " was not found";
    exit(1);
}

require_once $autoload_filename;

$app = new App(WAMBO_ROOT_DIR . '/src/config.php');
new FrontendRegistration($app);
new CartRegistration($app);
new CheckoutRegistration($app);
$app->add(new WhoopsMiddleware);

$app->run();